name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # Pacotes do projeto
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^0.13.5
  cupertino_icons: ^1.0.8
  intl: 0.17.0
  sqflite_common_ffi: ^2.3.0

  pdf: ^3.10.4
  printing: ^5.11.0
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/grafico.png
